# Generated by Django 4.2.5 on 2023-09-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('fullname', models.CharField(max_length=300, verbose_name='Fullname')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('response', models.TextField(verbose_name='Response')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Forms',
            },
        ),
    ]
